<a href="https://colab.research.google.com/github/A-l-E-v/ML-Engineer/blob/main/request_3_4_%D0%BA%D0%BE%D0%BD%D1%81%D0%BF%D0%B5%D0%BA%D1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ваш первый get-запрос

Чтобы получить данные с сервера, вам понадобится метод get(). Для отправления HTTP-запросов подключают библиотеку requests (англ. «запросы»).

In [ ]:
# Импортируем библиотеку
import requests

Прежде всего, нужна ссылка на сайт или URL (от англ. Uniform Resource Locator — «единый указатель ресурса»). Этой аббревиатурой обозначают адрес объекта в интернете.   
Для примера возьмем страничку на википедии про python: https://ru.wikipedia.org/wiki/Python

In [ ]:
# Сохраним ссылку в переменной URL
URL = 'https://ru.wikipedia.org/wiki/Python'

Метод get() библиотеки Requests выступает в роли имитации запроса от браузера. Передадим ему ссылку на сайт как аргумент. Метод отправит get-запрос на сервер, обработает полученный оттуда результат и вернёт объект response (англ. «ответ»), содержащий ответ сервера на HTTP-запрос.

In [ ]:
# сохраняем объект Response в переменную resp
resp = requests.get(URL)

Атрибут status_code (от англ. «код состояния») отвечает на вопрос: отправил сервер ответ или возникла какая-то ошибка.

In [ ]:
# Выведем код состояния ответа
print(resp.status_code)

200


200 - этот код означает, что запрос отработал корректно и ответ получен.

Объект Response содержит ответ сервера:
* код состояния
* содержание запроса
* код самой HTML-страницы  

Атрибуты объекта Response позволяют выводить не все данные из ответа, а только нужные для анализа. Название атрибута пишут после объекта Response, разделяя точкой


In [ ]:
# аттрибут text содержит лишь текстовое содержание запроса
print(resp.text)

<body></body><script nonce='f0e45464029ab947cf38497e92471337'>var it = {"host":"https:\u002F\u002Fsso.ya.ru\u002Finstall?uuid=9f1d2225-7e23-4155-b171-7988c74f41ff","retpath":"https:\u002F\u002Fya.ru\u002F?nr=1&redirect_ts=1690408575.00000"};(function() { var form = document.createElement('form'); var element1 = document.createElement('input'); var element2 = document.createElement('input'); element1.name = 'retpath'; element1.type = 'hidden'; element1.value = it.retpath; form.appendChild(element1); element2.name = 'container'; element2.type = 'hidden'; element2.value = '1690408635.10137725.oljfR5-8O5h3I4F4.NE_xFQG_h4R2gleYk5vV17lTZg5duFVbyglwqe-yQSqBaCTLar-8EYq_MAJDn99qPYES7L8CF2ksO9ybwqomWlYJvHy5mDVHKJA6xlGIIxI7m8tr8T0ZNYmE0uBhCNXQb2TO3NGwDtnydqgaZPH31rbbX4KDrUoflQP3ogkjr7LT67zQrI91cqVXCGGxQkXemswaFkQH8qgUY0n_gjhvhWsHhXrTNk_rPorxERPDGHnK1nuFjlhLc2QKUJZ04ZwYA9GsNR0sKus-YJKDeIACKmMO0ULQ85HAL7rVrprdTrqERUn4qFdbQz_rTsX2jIBqXqybRdw2lBpRKwWxb1S-wtI2I6cSrs7s_oYoriRXJwl6yADQT54Ki_pHn1ksDkLPJU

Выглядит угрожающе и непонятно, но не пугайтесь: во-первых, нам пока это еще не нужно, а во-вторых, скоро вы научитесь свободно ориентироваться в этом хаосе.

## Какие проблемы бывают в сети?

Попробуем посмотреть как блиблиотека поведет себя с другими сайтами.

In [ ]:
# Для удобства создадим вспомогательную функцию, которая выполняет get-запрос и выводит статус код
def my_get:
    response = requests.get(URL)
    print(response.status_code)
    return response

### 403

Попробуем отправить запрос к известному интернет-магазину.

In [ ]:
# попробуем "постучаться" в сайт озона
URL = "https://www.ozon.ru/"
resp = my_get(URL)

403


403 - код, означающий, что доступ запрещен. Это та самая защита от веб-майнинга, про кототорую мы говорили ранее. В простых случаях ее можно обойти с помощью хитростей или с помощью фреймворка selenium. Однако в случае крупной фирмы, вроде Озона, это может не помочь.

### 404

Посмотрим, что выведет запрос на несущесвтующую страницу на википедии.

In [ ]:
# кинем запрос на несуществующую страницу, существующего сайта
URL = "https://ru.wikipedia.org/wiki/non_exist"
resp = my_get(URL)

404


404 - Not Found. Страница не найдена. Это самая частая интернет ошибка.

### error

Попробуем обратиться к несуществующему сайту.

In [ ]:
# кинем запрос на несуществующий сайт
URL = "https://www.non_exist.ru"
resp = my_get(URL)

ConnectionError: HTTPSConnectionPool(host='www.non_exist.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002091CB49480>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Получаем ворох ошибок:


*   ConnectionError
*   MaxRetryError



Подведем итоги. В ходе урока мы научились:
* писать просыте GET запросы
* какие бывают самые частые код состояния и ошибки